# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAXpp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='acc',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='score',
            name='max_pp',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='score',
            name='pp',
            field=models.IntegerField(default=20),
        ),
    ]
