# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAXpp', '0002_auto_20171010_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='player',
            field=models.CharField(default='axmin', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='acc',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AlterField(
            model_name='score',
            name='bpm',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='score',
            name='count_0',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='count_100',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='count_200',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='count_300',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='count_50',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='count_r300',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='length_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='length_sec',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='star_rating',
            field=models.FloatField(default=1),
        ),
    ]
