# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-14 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAXpp', '0004_auto_20180314_0048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
